### ISSUE TITLE
ORACC not dealing with ligatures

### ISSUE THREAD

**Issue by zarpanitu** [oracc/oracc#75]
I’m starting to lemmatize, and came across this issue: the lemmatizer doesn’t seem to deal with ligatures properly, e.g. {d}+EN and {d}+AG, which are standard in Neo-Babylonian. When I have names written with these DNs, the next dash gets dropped in the writing of the name, e.g.

@entry Bel-kaṣir [1] PN
@form {m}{d}+ENKAD₂ %akk-x-neobab $Bel-kaṣir
@sense PN 1
@end entry

@entry Nabu-ban-zeri [1] PN
@form {m}{d}+AGDU₃-NUMUN %akk-x-neobab $Nabu-ban-zeri
@sense PN 1
@end entry

**Comment by jnovotny-lmu** [comment]
Something similar happens when a determinative is in the middle of the word: a hyphen is dropped. For example, in ribo/babylon0: 00atf/Samsuiluna_007_Akk.atf:261:Q002224: (lem) no FORM `{giš}TUKUL.{giš}TUKULšu'; 1 match for kakkīšu[weapon]N in glossary ribo/babylon0:akk.
The two problems appear to be related.

**Comment by stinney** [comment]
quick update: I spent some time on this today but it is tricky; I'm out of commission tomorrow (Tuesday) but will return to it Wednesday

**Comment by zarpanitu** [comment]
Thanks!

**Comment by stinney** [comment]
I have done quite a bit of work to repair the ATF processor after the fixes for the less common grouping things like ligatures and determinatives nested inside the middle of logograms, and all of the test cases now pass muster. In addition, I have tested a couple of projects to try to ensure that nothing new is broken (again).  I've updated the processor on both Philly and Munich build machines, and I would ask you to report suspected problems that involve logograms and/or grouped graphemes (like corrections with !, alternations with /, and ligatures with +, for example).

**Comment by jnovotny-lmu** [comment]
Proper names are not displaying properly in the Oracc **pager** (main pager, glossaries, etc.) as a result of the changes made to the ATF processor. 
There seem to be at least four problems. 
**1:** Hyphens separating logograms and phonetic-value signs are removed. For example, RIBo/Babylon7 Q005386 (= Neriglissar 1) i 11: `{m}{d}EN-šu-um-iš-ku-un` displays as `mdENšu-um-iš-ku-un` (without hyphen between `EN` and `EN`). 

**2:** Hyphens separating logograms from other logograms are replaced with dots (.)  
For example, RIBo/Babylon7 Q005388 (= Neriglissar 3) i 14 `{d}EN-MU-IN.GAR` displays as `dEN.MU.IN.GAR` (with dots rather than hyphens).

 **3:** Em-dash added after names in SAAo. For example, SAAo/assyrianletters (on Munich server) P313876 (= SAA 01 003) obverse 5' `{1}EN--BAD3` displays as `mEN.BÀD—`. This issue also exhibits the display problem of number 2 above, in addition to the final em-dash.

 **4:** Hyphens removed when pound sign appears before hyphen (for non-unicode files). For example, SAAo/assyrianletters (on Munich server) P313876 (= SAA 01 003) obverse 1' `[x x x x]+x#-ka#` displays as `[x x x x] ⸢xka⸣`. Note also the missing plus sign.

**Comment by lauriepearce** [comment]
In output, some hyphens have disappeared between logogram followed by syllabic sign.  See, for examples: P342311 (NCTU 08), o2: {m}{d}60-DINGIR]su-E  and {m}{d}ENszu2-[nu]; o10: {m}SALs,a-bit.

I have checked the ATF and the hyphens are present.

**Comment by stinney** [comment]
I've fixed all of the missing/malformed renderings reported in the last few messages.  One small point is that the missing '+' in x]+x# is intentional as this was an idiom we introduced to handle SAA legacy data and is an implemented as an approximation of x]x.  I'm still keeping this issue open because there may be more of these to find still.

**Comment by stinney** [comment]
Affect projects will need rebuilding

**Comment by jnovotny-lmu** [comment]
Numerous display errors still persist in the SAA projects. Transliterations are being displayed correctly in the glossaries, but not in the item view.
Here are representative examples:

**1.** saao/sargonletters, SAA 01 001 = P224485: The file has `a--dan-nisz` but it is displayed in the item view as `adan-niš`.

**2.** saao/sargonletters, SAA 05 169 = P334149: The file has `{1}{d}15--MU--BA-sza2` but it is displayed in the item view as `md15MU—BA-šá`.

**3.** saao/sargonletters, SAA 05 171 = P334321: The file has `{1}a-bat--LUGAL--PAB` but it is displayed in the item view as `ma-batLUGAL—PAB`.

For SAA legacy data it appears that `--` fails in the following instances in the item view of the pager:
**a:** syllabic sign followed by logographic sign or determinative.
**b:** syllabic sign followed by syllabic sign.
**c:** number followed by logographic sign. [It is possible that logographic sign followed by number might also fail.]

**Comment by stinney** [comment]
In SAAo mode the ATF processor now uses a literal em-dash on the g:delim attribute instead of "--", which means that the em-dash should always be output correctly in the pager.

**Comment by jnovotny-lmu** [comment]
Display issues still persist in [http://oracc.ub.uni-muenchen.de/saao/esarletters/pager](url). I believe that this is related to a different issue and will open a new bug, rather than report matters here.

**Comment by niekveldhuis** [comment]
Lemmatizer/checker ignores the first sign of a word between <(...)>. This is commonly used in bilingual lexical texts where the same (Akkadian) word is repeated and represented by MIN. 
1. [...] MIN<(ṣib-tu)>
#lem: +ṣibtu[interest]N$

gets picked up as
@entry ṣibtu [interest] N
@form tu $ṣibtu
etc.

Accordingly, correctly lemmatized forms like this get flagged as unknown. I assume this is still part of the same issue - if not I can open a new one.

Niek

**Comment by niekveldhuis** [comment]
related: curly brackets within <()> (as in <({d}ša₂-maš)> trigger "mismatched {...}" error as well as "internal error: word_form_index lookup failed".

**Comment by jnovotny-lmu** [comment]
Another example of this is in RIAo/ShalmaneserIII011.atf. 
Line 19', has `19'.	DUMU {m}<<{m}>>MAN-aš-šur ($traces$)`
`#lem: mār[son]N; Puzur-Aššur_II[vice-regent of Aššur, son of Sargon I]RN$Puzur-Aššur`
and the following error is reported: 
`ShalmaneserIII011.atf:123: (lem) no FORM {m}{}MAN-aš-šur and no matches for Puzur-Aššur_II[vice-regent of Aššur, son of Sargon I]RN in glossary riao:akk`. 
This is related to the problem reported by Niek.

**Comment by zarpanitu** [comment]
I've just noted what may be a related issue. It occurs when I have two successive phonetic complements: the “dash” between them gets put at the end, e.g.

Written forms:md+U.GUR-LUGALani-. 
Normalized forms:Nergal-šarrani (md+U.GUR-LUGALani-).

Should be: md+U.GUR-LUGAL-a-ni
